version: '3.8'

services: 
  # Cf. https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  backend:
    container_name: gazetteer-backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - cluster.name=gazetteer
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx4096m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./backend/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    networks:
      - gazetteer

  api:
    container_name: gazetteer-api
    build: 
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - gazetteer
    depends_on:
      - backend
 
networks:
  gazetteer:
